SMK-1220 / Added new functionalities
smarkio/bot-framework-bot-graph-dialog pull request #1
Opened 2017-02-22 17:21 UTC by Highvolt

* Updated to last version of bot framework.
* Added validations as middleware
* Added Value Parsers as middleware
* Added possibility to node override the next node to be executed
* Added validation that used external functions (using nodejs sandboxes see: https://nodejs.org/api/vm.html)
* Added validation for response length
* Added parsers for date, time and email (this last one is mandatory, because bot framework is not consistent across all connectors)
* Support to handle an carrousel item selection

2017-02-22 17:26 UTC, Highvolt commented
Please release version 3.5

2017-02-24 17:56 UTC, ruicampos requested changes
Only point is about logging. As we discussed we can add a logger with the logging level based on an environment variable - default: INFO (if environment variable not found)

2017-02-24 17:56 UTC, ruicampos commented on lib/GraphDialog.js
>                  console.log('parser is ready');
shouldn't we have a 'debug' mode and log only when in debugging?

2017-02-24 17:56 UTC, ruicampos commented on lib/GraphDialog.js
>          console.log('get dialog');
Same point about logging.

2017-02-24 17:56 UTC, ruicampos commented on lib/GraphDialog.js
>                  console.log('calling loop function');
logging point...

2017-02-24 17:56 UTC, ruicampos commented on lib/GraphDialog.js
> +        console.log(`perform action: ${currentNode.id}, ${currentNode.type}`);
logging point...

2017-02-24 18:16 UTC, ruicampos approved these changes
I will merge the PR and logging can be changed in next issue.

2017-02-24 18:16 UTC, merged